package com.af9.core.droppod.client;

import com.af9.core.AF9Core;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.resources.ResourceLocation;

/**
 * The drop pod: an octagonal capsule on four thrusters, white hull waist high, a roof on eight posts, a stepped dome, a
 * door that slides up at the front and a restraint bar that lifts out of the way when it lands. The boxes and the
 * texture come from {@code tools/textures/drop_pod.py} ({@link DropPodGeometry} is generated by it).
 */
public final class DropPodModel {

    public static final ModelLayerLocation LAYER = new ModelLayerLocation(
            new ResourceLocation(AF9Core.MOD_ID, "drop_pod"), "main");

    private final ModelPart root;
    private final ModelPart door;
    private final ModelPart restraint;
    private final float doorRest;
    private final float restraintY;
    private final float restraintZ;

    public DropPodModel(ModelPart root) {
        this.root = root;
        ModelPart pod = root.getChild("pod");
        this.door = pod.getChild("door");
        this.restraint = pod.getChild("restraint");
        this.doorRest = door.y;
        this.restraintY = restraint.y;
        this.restraintZ = restraint.z;
    }

    public static LayerDefinition createLayer() {
        return DropPodGeometry.layer();
    }

    /** 0 closed .. 1 open (model y is down: up is negative). */
    public void setup(float open) {
        door.y = doorRest - 22F * open;
        restraint.y = restraintY - 16F * open;
        restraint.z = restraintZ + 3F * open;
    }

    public void render(PoseStack stack, VertexConsumer consumer, int light, int overlay) {
        root.render(stack, consumer, light, overlay, 1F, 1F, 1F, 1F);
    }
}
