package com.af9.core.droppod.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * GENERATED by tools/textures/drop_pod.py (the boxes of the pod and their places on the 128 x 225 texture): do not edit
 * by hand, change the table in the script and run it again.
 */
final class DropPodGeometry {

    static final int TEXTURE_WIDTH = 128;
    static final int TEXTURE_HEIGHT = 225;

    private DropPodGeometry() {}

    static LayerDefinition layer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition pod = mesh.getRoot().addOrReplaceChild("pod", CubeListBuilder.create(), PartPose.offset(0, 24, 0));
        pod.addOrReplaceChild("bell_lb", CubeListBuilder.create().texOffs(36, 177)
                .addBox(-4.0F, -1.5F, -4.0F, 8F, 3F, 8F, new CubeDeformation(0.000F)),
                PartPose.offsetAndRotation(8.000F, -1.500F, -8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("nozzle_lb", CubeListBuilder.create().texOffs(100, 190)
                .addBox(-3.0F, -1.5F, -3.0F, 6F, 3F, 6F, new CubeDeformation(0.004F)),
                PartPose.offsetAndRotation(8.000F, -4.500F, -8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("strut_lb", CubeListBuilder.create().texOffs(68, 177)
                .addBox(-1.5F, -4.0F, -1.5F, 3F, 8F, 3F, new CubeDeformation(0.008F)),
                PartPose.offsetAndRotation(12.000F, -6.000F, -12.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("pad_lb", CubeListBuilder.create().texOffs(0, 201)
                .addBox(-3.5F, -1.0F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.012F)),
                PartPose.offsetAndRotation(14.000F, -1.000F, -14.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("bell_lf", CubeListBuilder.create().texOffs(80, 177)
                .addBox(-4.0F, -1.5F, -4.0F, 8F, 3F, 8F, new CubeDeformation(0.016F)),
                PartPose.offsetAndRotation(8.000F, -1.500F, 8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("nozzle_lf", CubeListBuilder.create().texOffs(28, 201)
                .addBox(-3.0F, -1.5F, -3.0F, 6F, 3F, 6F, new CubeDeformation(0.020F)),
                PartPose.offsetAndRotation(8.000F, -4.500F, 8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("strut_lf", CubeListBuilder.create().texOffs(112, 177)
                .addBox(-1.5F, -4.0F, -1.5F, 3F, 8F, 3F, new CubeDeformation(0.024F)),
                PartPose.offsetAndRotation(12.000F, -6.000F, 12.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("pad_lf", CubeListBuilder.create().texOffs(52, 201)
                .addBox(-3.5F, -1.0F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.028F)),
                PartPose.offsetAndRotation(14.000F, -1.000F, 14.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("bell_rb", CubeListBuilder.create().texOffs(0, 190)
                .addBox(-4.0F, -1.5F, -4.0F, 8F, 3F, 8F, new CubeDeformation(0.032F)),
                PartPose.offsetAndRotation(-8.000F, -1.500F, -8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("nozzle_rb", CubeListBuilder.create().texOffs(80, 201)
                .addBox(-3.0F, -1.5F, -3.0F, 6F, 3F, 6F, new CubeDeformation(0.036F)),
                PartPose.offsetAndRotation(-8.000F, -4.500F, -8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("strut_rb", CubeListBuilder.create().texOffs(32, 190)
                .addBox(-1.5F, -4.0F, -1.5F, 3F, 8F, 3F, new CubeDeformation(0.040F)),
                PartPose.offsetAndRotation(-12.000F, -6.000F, -12.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("pad_rb", CubeListBuilder.create().texOffs(0, 210)
                .addBox(-3.5F, -1.0F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.044F)),
                PartPose.offsetAndRotation(-14.000F, -1.000F, -14.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("bell_rf", CubeListBuilder.create().texOffs(44, 190)
                .addBox(-4.0F, -1.5F, -4.0F, 8F, 3F, 8F, new CubeDeformation(0.048F)),
                PartPose.offsetAndRotation(-8.000F, -1.500F, 8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("nozzle_rf", CubeListBuilder.create().texOffs(28, 210)
                .addBox(-3.0F, -1.5F, -3.0F, 6F, 3F, 6F, new CubeDeformation(0.052F)),
                PartPose.offsetAndRotation(-8.000F, -4.500F, 8.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("strut_rf", CubeListBuilder.create().texOffs(76, 190)
                .addBox(-1.5F, -4.0F, -1.5F, 3F, 8F, 3F, new CubeDeformation(0.056F)),
                PartPose.offsetAndRotation(-12.000F, -6.000F, 12.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("pad_rf", CubeListBuilder.create().texOffs(52, 210)
                .addBox(-3.5F, -1.0F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.060F)),
                PartPose.offsetAndRotation(-14.000F, -1.000F, 14.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("keel", CubeListBuilder.create().texOffs(24, 159)
                .addBox(-7.0F, -1.5F, -7.0F, 14F, 3F, 14F, new CubeDeformation(0.064F)),
                PartPose.offsetAndRotation(0.000F, -4.500F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("floor_a", CubeListBuilder.create().texOffs(0, 0)
                .addBox(-11.0F, -1.5F, -11.0F, 22F, 3F, 22F, new CubeDeformation(0.068F)),
                PartPose.offsetAndRotation(0.000F, -7.500F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("floor_b", CubeListBuilder.create().texOffs(0, 25)
                .addBox(-11.0F, -1.5F, -11.0F, 22F, 3F, 22F, new CubeDeformation(0.072F)),
                PartPose.offsetAndRotation(0.000F, -7.500F, 0.000F, 0.00000F, 0.78540F, 0.00000F));
        pod.addOrReplaceChild("hull_back", CubeListBuilder.create().texOffs(88, 75)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.076F)),
                PartPose.offsetAndRotation(0.000F, -18.000F, -11.000F, 0.00000F, 3.14159F, 0.00000F));
        pod.addOrReplaceChild("hull_back_l", CubeListBuilder.create().texOffs(0, 100)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.080F)),
                PartPose.offsetAndRotation(7.800F, -18.000F, -7.800F, 0.00000F, 2.35619F, 0.00000F));
        pod.addOrReplaceChild("hull_back_r", CubeListBuilder.create().texOffs(24, 100)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.084F)),
                PartPose.offsetAndRotation(-7.800F, -18.000F, -7.800F, 0.00000F, -2.35619F, 0.00000F));
        pod.addOrReplaceChild("hull_left", CubeListBuilder.create().texOffs(48, 100)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.088F)),
                PartPose.offsetAndRotation(11.000F, -18.000F, 0.000F, 0.00000F, 1.57080F, 0.00000F));
        pod.addOrReplaceChild("hull_right", CubeListBuilder.create().texOffs(72, 100)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.092F)),
                PartPose.offsetAndRotation(-11.000F, -18.000F, 0.000F, 0.00000F, -1.57080F, 0.00000F));
        pod.addOrReplaceChild("hull_front_l", CubeListBuilder.create().texOffs(96, 100)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.096F)),
                PartPose.offsetAndRotation(7.800F, -18.000F, 7.800F, 0.00000F, 0.78540F, 0.00000F));
        pod.addOrReplaceChild("hull_front_r", CubeListBuilder.create().texOffs(0, 120)
                .addBox(-5.0F, -9.0F, -1.0F, 10F, 18F, 2F, new CubeDeformation(0.100F)),
                PartPose.offsetAndRotation(-7.800F, -18.000F, 7.800F, 0.00000F, -0.78540F, 0.00000F));
        pod.addOrReplaceChild("seat", CubeListBuilder.create().texOffs(60, 140)
                .addBox(-5.0F, -8.0F, -1.0F, 10F, 16F, 2F, new CubeDeformation(0.104F)),
                PartPose.offsetAndRotation(0.000F, -18.000F, -8.500F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_a_-1_-1", CubeListBuilder.create().texOffs(84, 140)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.108F)),
                PartPose.offsetAndRotation(4.600F, -35.000F, -11.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_b_-1_-1", CubeListBuilder.create().texOffs(92, 140)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.112F)),
                PartPose.offsetAndRotation(11.200F, -35.000F, -4.600F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_a_-1_1", CubeListBuilder.create().texOffs(100, 140)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.116F)),
                PartPose.offsetAndRotation(4.600F, -35.000F, 11.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_b_-1_1", CubeListBuilder.create().texOffs(108, 140)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.120F)),
                PartPose.offsetAndRotation(11.200F, -35.000F, 4.600F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_a_1_-1", CubeListBuilder.create().texOffs(116, 140)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.124F)),
                PartPose.offsetAndRotation(-4.600F, -35.000F, -11.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_b_1_-1", CubeListBuilder.create().texOffs(0, 159)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.128F)),
                PartPose.offsetAndRotation(-11.200F, -35.000F, -4.600F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_a_1_1", CubeListBuilder.create().texOffs(8, 159)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.132F)),
                PartPose.offsetAndRotation(-4.600F, -35.000F, 11.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("post_b_1_1", CubeListBuilder.create().texOffs(16, 159)
                .addBox(-1.0F, -8.0F, -1.0F, 2F, 16F, 2F, new CubeDeformation(0.136F)),
                PartPose.offsetAndRotation(-11.200F, -35.000F, 4.600F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("roof_a", CubeListBuilder.create().texOffs(0, 50)
                .addBox(-11.0F, -1.5F, -11.0F, 22F, 3F, 22F, new CubeDeformation(0.140F)),
                PartPose.offsetAndRotation(0.000F, -44.500F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("roof_b", CubeListBuilder.create().texOffs(0, 75)
                .addBox(-11.0F, -1.5F, -11.0F, 22F, 3F, 22F, new CubeDeformation(0.144F)),
                PartPose.offsetAndRotation(0.000F, -44.500F, 0.000F, 0.00000F, 0.78540F, 0.00000F));
        pod.addOrReplaceChild("dome1_a", CubeListBuilder.create().texOffs(52, 120)
                .addBox(-7.5F, -2.0F, -7.5F, 15F, 4F, 15F, new CubeDeformation(0.148F)),
                PartPose.offsetAndRotation(0.000F, -48.000F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("dome1_b", CubeListBuilder.create().texOffs(0, 140)
                .addBox(-7.5F, -2.0F, -7.5F, 15F, 4F, 15F, new CubeDeformation(0.152F)),
                PartPose.offsetAndRotation(0.000F, -48.000F, 0.000F, 0.00000F, 0.78540F, 0.00000F));
        pod.addOrReplaceChild("dome2_a", CubeListBuilder.create().texOffs(80, 159)
                .addBox(-4.5F, -2.0F, -4.5F, 9F, 4F, 9F, new CubeDeformation(0.156F)),
                PartPose.offsetAndRotation(0.000F, -52.000F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("dome2_b", CubeListBuilder.create().texOffs(0, 177)
                .addBox(-4.5F, -2.0F, -4.5F, 9F, 4F, 9F, new CubeDeformation(0.160F)),
                PartPose.offsetAndRotation(0.000F, -52.000F, 0.000F, 0.00000F, 0.78540F, 0.00000F));
        pod.addOrReplaceChild("spike", CubeListBuilder.create().texOffs(88, 190)
                .addBox(-1.5F, -4.0F, -1.5F, 3F, 8F, 3F, new CubeDeformation(0.164F)),
                PartPose.offsetAndRotation(0.000F, -58.000F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("beacon", CubeListBuilder.create().texOffs(80, 210)
                .addBox(-1.5F, -1.5F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.168F)),
                PartPose.offsetAndRotation(0.000F, -63.500F, 0.000F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("light_l", CubeListBuilder.create().texOffs(46, 219)
                .addBox(-1.5F, -1.5F, -0.5F, 3F, 3F, 1F, new CubeDeformation(0.172F)),
                PartPose.offsetAndRotation(6.000F, -21.500F, 12.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("light_r", CubeListBuilder.create().texOffs(54, 219)
                .addBox(-1.5F, -1.5F, -0.5F, 3F, 3F, 1F, new CubeDeformation(0.176F)),
                PartPose.offsetAndRotation(-6.000F, -21.500F, 12.200F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("door", CubeListBuilder.create().texOffs(24, 120)
                .addBox(-6.0F, -9.0F, -1.0F, 12F, 18F, 2F, new CubeDeformation(0.180F)),
                PartPose.offsetAndRotation(0.000F, -18.000F, 11.800F, 0.00000F, 0.00000F, 0.00000F));
        pod.addOrReplaceChild("restraint", CubeListBuilder.create().texOffs(0, 219)
                .addBox(-10.0F, -1.5F, -1.5F, 20F, 3F, 3F, new CubeDeformation(0.184F)),
                PartPose.offsetAndRotation(0.000F, -28.000F, 9.000F, 0.00000F, 0.00000F, 0.00000F));
        return LayerDefinition.create(mesh, TEXTURE_WIDTH, TEXTURE_HEIGHT);
    }
}
