// AF9 - Area Simulation Chambers: crafting and simulation recipes. Spec: docs/area-simulation.md.
// Machines: startup_scripts/gtceu/area_simulation.js. An Area Data (kept) picks one of the seven
// areas, a programmed circuit the ore in it. Duration grows with the ore out (60-400 s).

ServerEvents.recipes(event => {
    const VA = GTValues.VA
    const HV = VA[GTValues.HV], EV = VA[GTValues.EV], IV = VA[GTValues.IV], LuV = VA[GTValues.LuV]
    const gt = event.recipes.gtceu

    // Anode Rods: copper-jacketed carbon rods the ore condenses on (used up).
    gt.assembler('af9:anode_rod')
        .itemInputs('4x minecraft:copper_ingot', '2x gtceu:carbon_fiber_plate')
        .itemOutputs('4x kubejs:anode_rod')
        .duration(200)
        .EUt(HV)

    // Lithium Gas: vaporised lithium, the third simulation gas.
    gt.electrolyzer('af9:lithium_gas')
        .itemInputs('gtceu:lithium_dust')
        .outputFluids(Fluid.of('gtceu:lithium_gas', 1000))
        .duration(200)
        .EUt(EV)

    // Area Data, one per area (kept): a data stick with the area's plates, at the area's voltage.
    const ascData = [
        ['overworld', 'iron', HV],
        ['nether', 'black_steel', HV],
        ['end', 'titanium', EV],
        ['moon', 'aluminium', EV],
        ['mars', 'stainless_steel', IV],
        ['venus', 'tungsten_steel', IV],
        ['asteroids', 'naquadah_alloy', LuV],
    ]
    ascData.forEach(([m, plate, eut]) => {
        gt.assembler(`af9:area_data_${m}`)
            .itemInputs('gtceu:data_stick', `4x gtceu:${plate}_plate`)
            .itemOutputs(`kubejs:area_data_${m}`)
            .duration(400)
            .EUt(eut)
    })

    // Chambers, HV-LuV: GT's electrolyzer of the tier, pumps, rods, filters, tier circuits.
    const ascTiers = ['hv', 'ev', 'iv', 'luv']
    ascTiers.forEach(t => {
        event.shaped(`gtceu:${t}_area_simulation_chamber`, ['RFR', 'PXP', 'CFC'], {
            R: 'kubejs:anode_rod',
            F: 'gtceu:fluid_filter',
            P: `gtceu:${t}_electric_pump`,
            X: `gtceu:${t}_electrolyzer`,
            C: `#gtceu:circuits/${t}`
        }).id(`af9:${t}_area_simulation_chamber`)
    })

    // ---- overworld (HV, 1 rod) ----
    gt.area_simulation('af9:asc_overworld_iron')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(1)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('8x minecraft:raw_iron')
        .duration(4400)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_copper')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(2)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('8x minecraft:raw_copper')
        .duration(4400)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_tin')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(3)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('16x gtceu:raw_tin')
        .duration(7600)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_coal')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(4)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('12x gtceu:raw_coal')
        .duration(6000)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_redstone')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(5)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('9x gtceu:raw_redstone')
        .duration(4800)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_magnetite')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(6)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('12x gtceu:raw_magnetite')
        .duration(6000)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_hematite')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(7)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('12x gtceu:raw_hematite')
        .duration(6000)
        .EUt(HV)
    gt.area_simulation('af9:asc_overworld_chalcopyrite')
        .notConsumable('kubejs:area_data_overworld')
        .circuit(8)
        .itemInputs('1x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 1000), Fluid.of('gtceu:carbon_dioxide', 500), Fluid.of('gtceu:lithium_gas', 250))
        .itemOutputs('13x gtceu:raw_chalcopyrite')
        .duration(6400)
        .EUt(HV)

    // ---- nether (HV, 2 rods) ----
    gt.area_simulation('af9:asc_nether_copper')
        .notConsumable('kubejs:area_data_nether')
        .circuit(1)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('7x minecraft:raw_copper')
        .duration(4000)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_gold')
        .notConsumable('kubejs:area_data_nether')
        .circuit(2)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('2x minecraft:raw_gold')
        .duration(2000)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_tetrahedrite')
        .notConsumable('kubejs:area_data_nether')
        .circuit(3)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('14x gtceu:raw_tetrahedrite')
        .duration(6800)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_sulfur')
        .notConsumable('kubejs:area_data_nether')
        .circuit(4)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('15x gtceu:raw_sulfur')
        .duration(7200)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_nether_quartz')
        .notConsumable('kubejs:area_data_nether')
        .circuit(5)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('12x gtceu:raw_nether_quartz')
        .duration(6000)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_wulfenite')
        .notConsumable('kubejs:area_data_nether')
        .circuit(6)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('8x gtceu:raw_wulfenite')
        .duration(4400)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_quartzite')
        .notConsumable('kubejs:area_data_nether')
        .circuit(7)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('6x gtceu:raw_quartzite')
        .duration(3600)
        .EUt(HV)
    gt.area_simulation('af9:asc_nether_beryllium')
        .notConsumable('kubejs:area_data_nether')
        .circuit(8)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000), Fluid.of('gtceu:carbon_dioxide', 1000), Fluid.of('gtceu:lithium_gas', 500))
        .itemOutputs('5x gtceu:raw_beryllium')
        .duration(3200)
        .EUt(HV)

    // ---- end (EV, 2 rods) ----
    gt.area_simulation('af9:asc_end_gold')
        .notConsumable('kubejs:area_data_end')
        .circuit(1)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('3x minecraft:raw_gold')
        .duration(2400)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_naquadah')
        .notConsumable('kubejs:area_data_end')
        .circuit(2)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('9x gtceu:raw_naquadah')
        .duration(4800)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_magnetite')
        .notConsumable('kubejs:area_data_end')
        .circuit(3)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('9x gtceu:raw_magnetite')
        .duration(4800)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_bauxite')
        .notConsumable('kubejs:area_data_end')
        .circuit(4)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('8x gtceu:raw_bauxite')
        .duration(4400)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_ilmenite')
        .notConsumable('kubejs:area_data_end')
        .circuit(5)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('4x gtceu:raw_ilmenite')
        .duration(2800)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_cooperite')
        .notConsumable('kubejs:area_data_end')
        .circuit(6)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('2x gtceu:raw_cooperite')
        .duration(2000)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_platinum')
        .notConsumable('kubejs:area_data_end')
        .circuit(7)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('2x gtceu:raw_platinum')
        .duration(2000)
        .EUt(EV)
    gt.area_simulation('af9:asc_end_scheelite')
        .notConsumable('kubejs:area_data_end')
        .circuit(8)
        .itemInputs('2x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 3000), Fluid.of('gtceu:carbon_dioxide', 1500), Fluid.of('gtceu:lithium_gas', 750))
        .itemOutputs('6x gtceu:raw_scheelite')
        .duration(3600)
        .EUt(EV)

    // ---- moon (EV, 3 rods) ----
    gt.area_simulation('af9:asc_moon_aluminium')
        .notConsumable('kubejs:area_data_moon')
        .circuit(1)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('4x gtceu:raw_aluminium')
        .duration(2800)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_ilmenite')
        .notConsumable('kubejs:area_data_moon')
        .circuit(2)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('4x gtceu:raw_ilmenite')
        .duration(2800)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_quartzite')
        .notConsumable('kubejs:area_data_moon')
        .circuit(3)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('6x gtceu:raw_quartzite')
        .duration(3600)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_certus_quartz')
        .notConsumable('kubejs:area_data_moon')
        .circuit(4)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('4x gtceu:raw_certus_quartz')
        .duration(2800)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_bauxite')
        .notConsumable('kubejs:area_data_moon')
        .circuit(5)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('8x gtceu:raw_bauxite')
        .duration(4400)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_magnetite')
        .notConsumable('kubejs:area_data_moon')
        .circuit(6)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('9x gtceu:raw_magnetite')
        .duration(4800)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_tin')
        .notConsumable('kubejs:area_data_moon')
        .circuit(7)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('16x gtceu:raw_tin')
        .duration(7600)
        .EUt(EV)
    gt.area_simulation('af9:asc_moon_silver')
        .notConsumable('kubejs:area_data_moon')
        .circuit(8)
        .itemInputs('3x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 4000), Fluid.of('gtceu:carbon_dioxide', 2000), Fluid.of('gtceu:lithium_gas', 1000))
        .itemOutputs('4x gtceu:raw_silver')
        .duration(2800)
        .EUt(EV)

    // ---- mars (IV, 4 rods) ----
    gt.area_simulation('af9:asc_mars_hematite')
        .notConsumable('kubejs:area_data_mars')
        .circuit(1)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('12x gtceu:raw_hematite')
        .duration(6000)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_goethite')
        .notConsumable('kubejs:area_data_mars')
        .circuit(2)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('5x gtceu:raw_goethite')
        .duration(3200)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_yellow_limonite')
        .notConsumable('kubejs:area_data_mars')
        .circuit(3)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('12x gtceu:raw_yellow_limonite')
        .duration(6000)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_malachite')
        .notConsumable('kubejs:area_data_mars')
        .circuit(4)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('6x gtceu:raw_malachite')
        .duration(3600)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_sulfur')
        .notConsumable('kubejs:area_data_mars')
        .circuit(5)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('15x gtceu:raw_sulfur')
        .duration(7200)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_pyrite')
        .notConsumable('kubejs:area_data_mars')
        .circuit(6)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('10x gtceu:raw_pyrite')
        .duration(5200)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_redstone')
        .notConsumable('kubejs:area_data_mars')
        .circuit(7)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('9x gtceu:raw_redstone')
        .duration(4800)
        .EUt(IV)
    gt.area_simulation('af9:asc_mars_iron')
        .notConsumable('kubejs:area_data_mars')
        .circuit(8)
        .itemInputs('4x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 5000), Fluid.of('gtceu:carbon_dioxide', 2500), Fluid.of('gtceu:lithium_gas', 1250))
        .itemOutputs('8x minecraft:raw_iron')
        .duration(4400)
        .EUt(IV)

    // ---- venus (IV, 5 rods) ----
    gt.area_simulation('af9:asc_venus_sulfur')
        .notConsumable('kubejs:area_data_venus')
        .circuit(1)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('15x gtceu:raw_sulfur')
        .duration(7200)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_pyrite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(2)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('10x gtceu:raw_pyrite')
        .duration(5200)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_tetrahedrite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(3)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('14x gtceu:raw_tetrahedrite')
        .duration(6800)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_wulfenite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(4)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('8x gtceu:raw_wulfenite')
        .duration(4400)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_molybdenite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(5)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('5x gtceu:raw_molybdenite')
        .duration(3200)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_powellite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(6)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('3x gtceu:raw_powellite')
        .duration(2400)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_barite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(7)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('2x gtceu:raw_barite')
        .duration(2000)
        .EUt(IV)
    gt.area_simulation('af9:asc_venus_quartzite')
        .notConsumable('kubejs:area_data_venus')
        .circuit(8)
        .itemInputs('5x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 6000), Fluid.of('gtceu:carbon_dioxide', 3000), Fluid.of('gtceu:lithium_gas', 1500))
        .itemOutputs('6x gtceu:raw_quartzite')
        .duration(3600)
        .EUt(IV)

    // ---- asteroids (LuV, 6 rods) ----
    gt.area_simulation('af9:asc_asteroids_brannerite')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(1)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('4x gtceu:raw_brannerite')
        .duration(2800)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_magnetite')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(2)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('9x gtceu:raw_magnetite')
        .duration(4800)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_pentlandite')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(3)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('4x gtceu:raw_pentlandite')
        .duration(2800)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_cooperite')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(4)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('2x gtceu:raw_cooperite')
        .duration(2000)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_naquadah')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(5)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('9x gtceu:raw_naquadah')
        .duration(4800)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_platinum')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(6)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('2x gtceu:raw_platinum')
        .duration(2000)
        .EUt(LuV)
    gt.area_simulation('af9:asc_asteroids_oil_regolith')
        .notConsumable('kubejs:area_data_asteroids')
        .circuit(7)
        .itemInputs('6x kubejs:anode_rod')
        .inputFluids(Fluid.of('gtceu:hydrogen', 7000), Fluid.of('gtceu:carbon_dioxide', 3500), Fluid.of('gtceu:lithium_gas', 1750))
        .itemOutputs('4x af9:oil_regolith')
        .duration(2800)
        .EUt(LuV)
})
